// This file is @generated by prost-build.
/// Synthesis request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynthesizeRequest {
    /// Text to synthesize (required)
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    /// Target language (optional, defaults to RU)
    #[prost(enumeration = "Language", tag = "2")]
    pub language: i32,
    /// Speaker ID for multi-speaker models (optional)
    #[prost(uint32, optional, tag = "3")]
    pub speaker_id: ::core::option::Option<u32>,
    /// Output audio format (optional, defaults to PCM_S16LE)
    #[prost(enumeration = "AudioFormat", tag = "4")]
    pub audio_format: i32,
    /// Sample rate in Hz (optional, defaults to 24000)
    #[prost(uint32, tag = "5")]
    pub sample_rate: u32,
    /// Random seed for deterministic generation (optional)
    #[prost(uint64, optional, tag = "6")]
    pub seed: ::core::option::Option<u64>,
    /// Request ID for tracking (optional)
    #[prost(string, tag = "7")]
    pub request_id: ::prost::alloc::string::String,
}
/// Synthesis response (unary)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SynthesizeResponse {
    /// Audio data
    #[prost(bytes = "vec", tag = "1")]
    pub audio_data: ::prost::alloc::vec::Vec<u8>,
    /// Audio format
    #[prost(enumeration = "AudioFormat", tag = "2")]
    pub audio_format: i32,
    /// Sample rate in Hz
    #[prost(uint32, tag = "3")]
    pub sample_rate: u32,
    /// Number of audio samples
    #[prost(uint64, tag = "4")]
    pub num_samples: u64,
    /// Audio duration in milliseconds
    #[prost(float, tag = "5")]
    pub duration_ms: f32,
    /// Processing time in milliseconds
    #[prost(float, tag = "6")]
    pub processing_time_ms: f32,
    /// Real-time factor (processing_time / audio_duration)
    #[prost(float, tag = "7")]
    pub rtf: f32,
    /// Request ID (echoed back)
    #[prost(string, tag = "8")]
    pub request_id: ::prost::alloc::string::String,
}
/// Audio chunk for streaming
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AudioChunk {
    /// Chunk index (0-based)
    #[prost(uint32, tag = "1")]
    pub chunk_index: u32,
    /// Audio data for this chunk
    #[prost(bytes = "vec", tag = "2")]
    pub audio_data: ::prost::alloc::vec::Vec<u8>,
    /// Sample rate in Hz
    #[prost(uint32, tag = "3")]
    pub sample_rate: u32,
    /// Number of samples in this chunk
    #[prost(uint32, tag = "4")]
    pub num_samples: u32,
    /// Start time of this chunk in milliseconds
    #[prost(float, tag = "5")]
    pub start_ms: f32,
    /// Duration of this chunk in milliseconds
    #[prost(float, tag = "6")]
    pub duration_ms: f32,
    /// Is this the final chunk?
    #[prost(bool, tag = "7")]
    pub is_final: bool,
    /// Request ID (echoed back)
    #[prost(string, tag = "8")]
    pub request_id: ::prost::alloc::string::String,
}
/// Health check request
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
/// Health check response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    #[prost(enumeration = "health_response::Status", tag = "1")]
    pub status: i32,
    /// Service version
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// Uptime in seconds
    #[prost(uint64, tag = "3")]
    pub uptime_seconds: u64,
}
/// Nested message and enum types in `HealthResponse`.
pub mod health_response {
    /// Service status
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        Unspecified = 0,
        Serving = 1,
        NotServing = 2,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "STATUS_UNSPECIFIED",
                Self::Serving => "STATUS_SERVING",
                Self::NotServing => "STATUS_NOT_SERVING",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STATUS_UNSPECIFIED" => Some(Self::Unspecified),
                "STATUS_SERVING" => Some(Self::Serving),
                "STATUS_NOT_SERVING" => Some(Self::NotServing),
                _ => None,
            }
        }
    }
}
/// Info request
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InfoRequest {}
/// Info response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InfoResponse {
    /// Service name
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Service version
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    /// Model name
    #[prost(string, tag = "3")]
    pub model_name: ::prost::alloc::string::String,
    /// Supported languages
    #[prost(enumeration = "Language", repeated, tag = "4")]
    pub supported_languages: ::prost::alloc::vec::Vec<i32>,
    /// Default sample rate
    #[prost(uint32, tag = "5")]
    pub default_sample_rate: u32,
    /// Maximum text length
    #[prost(uint32, tag = "6")]
    pub max_text_length: u32,
    /// Number of available speakers
    #[prost(uint32, tag = "7")]
    pub num_speakers: u32,
}
/// Language enum
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Language {
    Unspecified = 0,
    Ru = 1,
    En = 2,
    Mixed = 3,
}
impl Language {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LANGUAGE_UNSPECIFIED",
            Self::Ru => "LANGUAGE_RU",
            Self::En => "LANGUAGE_EN",
            Self::Mixed => "LANGUAGE_MIXED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LANGUAGE_UNSPECIFIED" => Some(Self::Unspecified),
            "LANGUAGE_RU" => Some(Self::Ru),
            "LANGUAGE_EN" => Some(Self::En),
            "LANGUAGE_MIXED" => Some(Self::Mixed),
            _ => None,
        }
    }
}
/// Audio format enum
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AudioFormat {
    Unspecified = 0,
    /// Raw PCM 16-bit signed little-endian
    PcmS16le = 1,
    /// WAV container
    Wav = 2,
}
impl AudioFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUDIO_FORMAT_UNSPECIFIED",
            Self::PcmS16le => "AUDIO_FORMAT_PCM_S16LE",
            Self::Wav => "AUDIO_FORMAT_WAV",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUDIO_FORMAT_UNSPECIFIED" => Some(Self::Unspecified),
            "AUDIO_FORMAT_PCM_S16LE" => Some(Self::PcmS16le),
            "AUDIO_FORMAT_WAV" => Some(Self::Wav),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod tts_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Text-to-Speech service
    #[derive(Debug, Clone)]
    pub struct TtsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TtsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TtsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TtsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            TtsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Synthesize text to audio (unary)
        pub async fn synthesize(
            &mut self,
            request: impl tonic::IntoRequest<super::SynthesizeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SynthesizeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tts.v1.TtsService/Synthesize",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tts.v1.TtsService", "Synthesize"));
            self.inner.unary(req, path, codec).await
        }
        /// Synthesize text to audio stream (server streaming)
        pub async fn synthesize_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::SynthesizeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AudioChunk>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tts.v1.TtsService/SynthesizeStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("tts.v1.TtsService", "SynthesizeStream"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get service health status
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/tts.v1.TtsService/Health");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("tts.v1.TtsService", "Health"));
            self.inner.unary(req, path, codec).await
        }
        /// Get service information
        pub async fn get_info(
            &mut self,
            request: impl tonic::IntoRequest<super::InfoRequest>,
        ) -> std::result::Result<tonic::Response<super::InfoResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/tts.v1.TtsService/GetInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("tts.v1.TtsService", "GetInfo"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod tts_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with TtsServiceServer.
    #[async_trait]
    pub trait TtsService: std::marker::Send + std::marker::Sync + 'static {
        /// Synthesize text to audio (unary)
        async fn synthesize(
            &self,
            request: tonic::Request<super::SynthesizeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SynthesizeResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the SynthesizeStream method.
        type SynthesizeStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AudioChunk, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Synthesize text to audio stream (server streaming)
        async fn synthesize_stream(
            &self,
            request: tonic::Request<super::SynthesizeRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SynthesizeStreamStream>,
            tonic::Status,
        >;
        /// Get service health status
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
        /// Get service information
        async fn get_info(
            &self,
            request: tonic::Request<super::InfoRequest>,
        ) -> std::result::Result<tonic::Response<super::InfoResponse>, tonic::Status>;
    }
    /// Text-to-Speech service
    #[derive(Debug)]
    pub struct TtsServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> TtsServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for TtsServiceServer<T>
    where
        T: TtsService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/tts.v1.TtsService/Synthesize" => {
                    #[allow(non_camel_case_types)]
                    struct SynthesizeSvc<T: TtsService>(pub Arc<T>);
                    impl<
                        T: TtsService,
                    > tonic::server::UnaryService<super::SynthesizeRequest>
                    for SynthesizeSvc<T> {
                        type Response = super::SynthesizeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SynthesizeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TtsService>::synthesize(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SynthesizeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/tts.v1.TtsService/SynthesizeStream" => {
                    #[allow(non_camel_case_types)]
                    struct SynthesizeStreamSvc<T: TtsService>(pub Arc<T>);
                    impl<
                        T: TtsService,
                    > tonic::server::ServerStreamingService<super::SynthesizeRequest>
                    for SynthesizeStreamSvc<T> {
                        type Response = super::AudioChunk;
                        type ResponseStream = T::SynthesizeStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SynthesizeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TtsService>::synthesize_stream(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SynthesizeStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/tts.v1.TtsService/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: TtsService>(pub Arc<T>);
                    impl<T: TtsService> tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TtsService>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/tts.v1.TtsService/GetInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetInfoSvc<T: TtsService>(pub Arc<T>);
                    impl<T: TtsService> tonic::server::UnaryService<super::InfoRequest>
                    for GetInfoSvc<T> {
                        type Response = super::InfoResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InfoRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as TtsService>::get_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for TtsServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "tts.v1.TtsService";
    impl<T> tonic::server::NamedService for TtsServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
